// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/cloudogu/k8s-auth-registration-lib/api/v1"
	apiv1 "github.com/cloudogu/k8s-auth-registration-lib/client/typed/api/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAuthRegistrations implements AuthRegistrationInterface
type fakeAuthRegistrations struct {
	*gentype.FakeClientWithList[*v1.AuthRegistration, *v1.AuthRegistrationList]
	Fake *FakeApiV1
}

func newFakeAuthRegistrations(fake *FakeApiV1, namespace string) apiv1.AuthRegistrationInterface {
	return &fakeAuthRegistrations{
		gentype.NewFakeClientWithList[*v1.AuthRegistration, *v1.AuthRegistrationList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("authregistrations"),
			v1.SchemeGroupVersion.WithKind("AuthRegistration"),
			func() *v1.AuthRegistration { return &v1.AuthRegistration{} },
			func() *v1.AuthRegistrationList { return &v1.AuthRegistrationList{} },
			func(dst, src *v1.AuthRegistrationList) { dst.ListMeta = src.ListMeta },
			func(list *v1.AuthRegistrationList) []*v1.AuthRegistration { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.AuthRegistrationList, items []*v1.AuthRegistration) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
