// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	apiv1 "github.com/cloudogu/k8s-auth-registration-lib/api/v1"
	scheme "github.com/cloudogu/k8s-auth-registration-lib/client/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AuthRegistrationsGetter has a method to return a AuthRegistrationInterface.
// A group's client should implement this interface.
type AuthRegistrationsGetter interface {
	AuthRegistrations(namespace string) AuthRegistrationInterface
}

// AuthRegistrationInterface has methods to work with AuthRegistration resources.
type AuthRegistrationInterface interface {
	Create(ctx context.Context, authRegistration *apiv1.AuthRegistration, opts metav1.CreateOptions) (*apiv1.AuthRegistration, error)
	Update(ctx context.Context, authRegistration *apiv1.AuthRegistration, opts metav1.UpdateOptions) (*apiv1.AuthRegistration, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, authRegistration *apiv1.AuthRegistration, opts metav1.UpdateOptions) (*apiv1.AuthRegistration, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*apiv1.AuthRegistration, error)
	List(ctx context.Context, opts metav1.ListOptions) (*apiv1.AuthRegistrationList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *apiv1.AuthRegistration, err error)
	AuthRegistrationExpansion
}

// authRegistrations implements AuthRegistrationInterface
type authRegistrations struct {
	*gentype.ClientWithList[*apiv1.AuthRegistration, *apiv1.AuthRegistrationList]
}

// newAuthRegistrations returns a AuthRegistrations
func newAuthRegistrations(c *ApiV1Client, namespace string) *authRegistrations {
	return &authRegistrations{
		gentype.NewClientWithList[*apiv1.AuthRegistration, *apiv1.AuthRegistrationList](
			"authregistrations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1.AuthRegistration { return &apiv1.AuthRegistration{} },
			func() *apiv1.AuthRegistrationList { return &apiv1.AuthRegistrationList{} },
		),
	}
}
